### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by yuyaYS** [FEMR/fEMR-OnChain-Core#541]
**Describe the bug**
Docker-compose up fails. 
The error message says _ModuleNotFoundError: No module named 'appMR.urls'_
Even though submodule install was success, it still give same error message.

**To Reproduce**
Initially, I installed docker.io and docker-compose from apt package, but I received same error above when I run docker-compose up. 
Then, I remove docker.io and docker-compose and installed docker/docker-compose following official guide. 

The following process is to install docker/docker-compose up, sync with submodule and run the application.

1. Go to [https://docs.docker.com/engine/install/ubuntu/](url) and install docker engine. 
Only change is that argument from **$(lsb_release -cs)** to **focal** in step 3, Set up the repository process.
2. Go to [https://docs.docker.com/compose/install/](url) and install docker-compose
3. Go to the OnChain-Core repo and change the branch to **dev**
4. sync with submodule repos. Run following commands. 
- `git submodule init `
- `git submodule set-url appMR https://github.com/Romulus10/AppMR.git`
- `git submodule set-url clinic_messages https://github.com/Romulus10/DjangoMessage.git`
- `git submodule update `
5. Run
 - `docker-compose up`

**Expected behavior**
It should install dependencies and build application.

**Desktop (please complete the following information):**
 - OS: linux mint 20.1(Ubuntu Focal)
 - Docker version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
 - docker-compose version 1.29.2, build 5becea4c

**Comment by Romulus10** [comment]
I put together a Linux Mint VM that recreates most of your environment, except it's running Mint 20.2 instead of 20.1.
I wasn't able to reproduce this problem.

Just counting out the weird problems - could you verify that `appMR/urls.py` actually exists and hasn't been lost in some crazy git accident?

**Comment by Romulus10** [comment]
I'll also give it a shot on 20.1.

**Comment by yuyaYS** [comment]
I checked appMR/urls.py and it was exactly same. Also, I don't think there has been weird accident in git.
I tested out Mint 20.1 on VM and it works!!!  Now just need to figure out why I am having trouble in my machine.

**Comment by Romulus10** [comment]
I didn't think there was anything weird with Git either honestly, I just wanted to count out anything we could think of. 

That's really interesting. If you do manage to figure out the difference, please do let me know so I can make sure it gets documented. It might be something as simple as an old version of a package somewhere.

**Comment by yuyaYS** [comment]
I found two commands from the official document.  
```
sudo rm -rf /var/lib/docker
```
```
sudo rm -rf /var/lib/containerd 
```
It is possibly due to the docker from apt package version was old and stayed /bin even after running remove command.

**Comment by yuyaYS** [comment]
Yes it is fixed.
