### ISSUE TITLE
System Requesting Password change at every log in

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#637]
Every time the user logs in, the system is requesting that the user change passwords. This should only happen after a password expires (which should happen every 90 days).

<img width="1440" alt="Screen Shot 2022-01-31 at 10 55 47 AM" src="https://user-images.githubusercontent.com/30377988/151827317-90af9df9-c3d3-4bb1-9c8a-37aa2352c265.png">

**Comment by Romulus10** [comment]
@sarahdraugelis ready for review.
