### ISSUE TITLE
Add watermarks to different environments

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#681]
Add watermarks to demarcate the difference between dev, training, and production environments.

**Comment by sarahdraugelis** [comment]
<img width="1440" alt="Screen Shot 2022-03-22 at 6 33 56 PM" src="https://user-images.githubusercontent.com/30377988/159587434-c9b308b7-c391-4383-8a0b-1e5de66346bb.png">

Logo is not appearing in the training environment (note upper left hand corner as well as central screen). I expanded the window and did not see a change.

**Comment by Romulus10** [comment]
I just opened this comment as a new issue. The changes reflected in this one aren't live in the training environment, so this is an independent problem.

**Comment by Romulus10** [comment]
Just checked this - it's looking good on my end. Can you confirm?

**Comment by sarahdraugelis** [comment]
So it looks great on dev, but still not showing up in training.




Regards,

Sarah Draugelis
President & Co-founder, Team fEMR
(810) 813-7923

**Comment by Romulus10** [comment]
It won't until we push v1.5.2 to training.

**Comment by sarahdraugelis** [comment]
Got it. In that case, looks great then! 

Regards,

Sarah Draugelis
President & Co-founder, Team fEMR
(810) 813-7923
