### ISSUE TITLE
Add Chief Complaint to Patient Export

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#690]
<img width="1440" alt="Screen Shot 2022-03-25 at 11 18 27 AM" src="https://user-images.githubusercontent.com/30377988/160149215-9cd207c2-ae03-4e45-8a77-f35dc873be4f.png">
<img width="1440" alt="Screen Shot 2022-03-25 at 11 18 36 AM" src="https://user-images.githubusercontent.com/30377988/160149253-26db4f8f-0155-418d-833a-6ecc159ef08f.png">
<img width="1440" alt="Screen Shot 2022-03-25 at 11 18 47 AM" src="https://user-images.githubusercontent.com/30377988/160149286-e452dcdf-21a5-438a-ad17-2d5bb6d82584.png">
<img width="1440" alt="Screen Shot 2022-03-25 at 11 18 55 AM" src="https://user-images.githubusercontent.com/30377988/160149316-83ddfcd4-daff-46d0-8d8e-67c9af2bff8f.png">

The Chief complain is not appearing upon patient export. This should be included by the top of each encounter history

**Comment by sarahdraugelis** [comment]
<img width="1440" alt="Screen Shot 2022-03-28 at 9 25 50 AM" src="https://user-images.githubusercontent.com/30377988/160407737-5eb2c0c2-e6c5-40c4-88fe-90eea90f7340.png">
<img width="1440" alt="Screen Shot 2022-03-28 at 9 26 24 AM" src="https://user-images.githubusercontent.com/30377988/160407861-f2f303cc-b0f4-4147-bf26-4e1f1873a2e1.png">

Chief complaint not shown

**Comment by Romulus10** [comment]
This was because there were chief complaints but no History of Present Illness records for them. I added a list at the top of the section that displays the encounter's chief complaints whether the HPI tab is filled out or not.

**Comment by Romulus10** [comment]
Chief encounters appear on the encounter they were reported for. So if you scroll down you should see a second encounter with the second chief complaint.
