### ISSUE TITLE
CSV export not working

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#783]
<img width="1440" alt="Screen Shot 2022-05-04 at 9 01 12 AM" src="https://user-images.githubusercontent.com/30377988/166686401-88bb92c6-0dc8-4abb-ac37-94c35a7db60d.png">

<img width="1440" alt="Screen Shot 2022-05-04 at 9 09 52 AM" src="https://user-images.githubusercontent.com/30377988/166687860-73909333-2128-4a24-9398-7e4038a9cf3e.png">

No error message, but the CSV was never exported. The last CSV export in my messages was from the 17th of April.

**Comment by sarahdraugelis** [comment]
<img width="1440" alt="Screen Shot 2022-05-04 at 8 29 05 PM" src="https://user-images.githubusercontent.com/30377988/166847872-0b04fe67-3bef-4176-bd46-7d4b342fcfa1.png">
still not working

**Comment by Romulus10** [comment]
![image](https://user-images.githubusercontent.com/11912069/167052991-dd29ec10-184d-4377-85b6-5f2c07a02f69.png)
It's not fast, but I've got CSV exports working.

**Comment by Romulus10** [comment]
Got another one too:
![image](https://user-images.githubusercontent.com/11912069/167053236-c4e11b4c-deec-468f-a39c-0e8553fad8ee.png)

**Comment by sarahdraugelis** [comment]
Still not working for me


<img width="1440" alt="Screen Shot 2022-05-06 at 8 50 21 AM" src="https://user-images.githubusercontent.com/30377988/167134644-798f682a-020f-41f1-b51b-419704e3d958.png">
